server:
  port: 8080

logging:
  config: classpath:log4j2.xml

spring:
  profiles:
    active: dev


#spring:
#  resources:
#    add-mappings: false
#spring:
#  mvc:
#    static-path-pattern: /swagger/**
#  resources:
#    static-locations: classpath:/static