server:
  port: 8080

spring:
  redis:
    host: 47.100.185.77
    port: 6379
    password: 373616885
    database: 8
    lettuce:
      pool:
        max-active: 50
        max-wait: 1000
        min-idle: 0
        max-idle: 8
    timeout: 1500