# DataSource Config
spring:
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/nacos?useUnicode=true&autoReconnect=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false&allowMultiQueries=true&failOverReadOnly=false&connectTimeout=1000&socketTimeout=3000&serverTimezone=GMT%2B8
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://47.100.185.77:3306/nacos?useUnicode=true&autoReconnect=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false&allowMultiQueries=true&failOverReadOnly=false&connectTimeout=1000&socketTimeout=3000&serverTimezone=GMT%2B8
    username: root
    password: 373616885
    hikari:
      auto-commit: true
      minimum-idle: 1
      maximum-pool-size: 10
      #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired）
      max-lifetime: 25200000
      connection-test-query: select 1 from dual

logging:
  config: classpath:log4j2.xml

mybatis-plus:
  # 自定义xml文件路径
  # maven 多模块项目的扫描路径需以 classpath* 开头（即加载多个jar包下的xml文件）
  mapper-locations: classpath*:com/qin/nacos/**/mapper/*Mapper.xml
  # config-location: classpath*:mybatis-config.xml
  # resultType 不需要输入全路径名
  type-aliases-package: com.qin.nacos.**.entity
  #枚举属性配置扫描
  type-enums-package: com.qin.nacos.**.enums
  # configuration 和 config-location 不能同时出现
  configuration:
    # 默认是true 驼峰自动映射 mybatis-plus默认是true  mybatis默认是false
    map-underscore-to-camel-case: true
    #mybatis返回map类型数据空值字段显示
    call-setters-on-nulls: true
  global-config:
    db-config:
      # 一般不需要配--默认根据url判断
      db-type: mysql
      id-type: AUTO
      # 表前缀名
      # table-prefix: t_