server:
  port: 4444

spring:
  application:
    name: client-4444

nacos:
  discovery:
    auto-register: true
    server-addr: 127.0.0.1:8848
    namespace: dev
    register:
      group-name: qinjp
      service-name: client
