
#server.port=9431
nacos:
  config:
    server-addr: 47.100.185.77:8848
    context-path: nacos
    namespace: dev
    data-id: nacos
    group: qin
    auto-refresh: true
    username: nacos
    password: nacos
    remote-first: true
    # \u5355\u72EC\u5728nacos\u4E2D\u6307\u5B9A\u7C7B\u578B
    # \u8FD8\u9700\u8981\u914D\u7F6E\u7684\u662Fnacos.config bootstrap.enable=true\u6216nacos.config bootstrap.log.enable=true
    # \u914D\u5408\u4F7F\u7528
    type: yaml
    bootstrap:
      enable: true
      log-enable: true


logging:
  level:
    root: info
