# DataSource Config
spring:
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    #&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/nacos?characterEncoding=utf8&useSSL=false&useUnicode=true&autoReconnect=true&rewriteBatchedStatements=true&useConfigs=maxPerformance&allowMultiQueries=true&failOverReadOnly=false&connectTimeout=1000&socketTimeout=3000&serverTimezone=Asia/Shanghai
    #driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/nacos?characterEncoding=utf8&useSSL=false&useUnicode=true&autoReconnect=true&rewriteBatchedStatements=true&useConfigs=maxPerformance&allowMultiQueries=true&failOverReadOnly=false&connectTimeout=1000&socketTimeout=3000&serverTimezone=Asia/Shanghai
    username: root
    password: 373616885
    hikari:
      auto-commit: true
      minimum-idle: 1
      maximum-pool-size: 10
      #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired）
      max-lifetime: 25200000
      connection-test-query: select 1 from dual

logging:
  config: classpath:log4j2.xml
