server:
  port: 8080

spring:
  application:
    name: fegin
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 47.100.185.77:8888
        namespace: dev
        group: group
        username: nacos
        password: nacos
        register-enabled: false

feign:
  client:
    config:
      default:           #\u670D\u52A1\u540D\uFF0C\u586B\u5199default\u4E3A\u6240\u6709\u670D\u52A1
        connectTimeout: 8000
        readTimeout: 8000







