spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.9.250:3306/qin?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&connectTimeout=1000&socketTimeout=3000&serverTimezone=GMT%2B8
    username: root
    password: 373616885
    hikari:
      auto-commit: true
      connection-timeout: 6000
      connection-test-query: select 1 from dual
      minimum-idle: 1
      maximum-pool-size: 50

mybatis:
  config-location: classpath:mybatis.xml
debug: true
server:
  port: 8888

logging:
  config: classpath:log4j2.xml