spring:
# DataSource Config
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://47.100.185.77:3306/mp?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&connectTimeout=1000&socketTimeout=3000&serverTimezone=GMT%2B8
    username: root
    password: 373616885

logging:
  config: classpath:log4j2.xml

mybatis-plus:
  # 自定义xml文件路径
  mapper-locations: classpath:com/qin/mp/mapper/*Mapper.xml